
server:
  port: 8090


api.key: my-api-key
api.secret: my-secret


capacity.requests: 3


gateway:
    publicEndpoints:
        /api/v1/example,
        /api/v1/another-example
#      - "mm"
#      - "kl"



SHELLs: dhsjhgjhgd

